export default {
    path:"/movie",
    component:()=>import("../../views/movie"),
    children:[
        {
            path:"city",
            component:()=>import("../../components/City")
        },
        {
            path:"Nowplaying",
            component:()=>import("../../components/Nowplaying")
        },
        {
            path:"ComingSoon",
            component:()=>import("../../components/ComingSoon")
        },
        {
            path:"Search",
            component:()=>import("../../components/Search")
        },
        {
            path:"detail/1/:id",
            components:{
                default:()=>import("../../components/Nowplaying"),
                detail:()=>import("../../views/movie/detail")
            },
            props:{
                detail:true
            }
        },
        {
            path:"detail/2/:id",
            components:{
                default:()=>import("../../components/ComingSoon"),
                detail:()=>import("../../views/movie/detail")
            },
            props:{
                detail:true
            }
        },
        {
            path:"/movie",
            redirect:"/movie/Nowplaying"
        }
    ]
}